spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/workers/**
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/payments/**
        - id: hr-user
          uri: lb://hr-user
          predicates:
            - Path=/users/**



# EUREKA CLIENT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765