spring:
  application:
    name: hr-payroll

# EUREKA CLIENT
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

  h2:
    console:
      enable: true
      path: /h2-console

server:
  port: 8101
