#spring:
#  application:
#    name: hr-worker
#
#  # Eureka server
#  eureka:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka
#
#  # Database configuration
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#
#server:
#  port: 8001
#
