spring:
  application:
    name: hr-worker

  # PROFILE ACTIVE
  profiles:
    active: dev

  # CONFIG SERVER NAME
  config:
    import: optional:configserver:http://localhost:8888/

  h2:
    console:
      enabled: true

    # CONFIG SERVER
#    cloud:
#      config:
#        name: config-server
#        uri: optional:configserver:http://localhost:8888
#        fail-fast: true

# EUREKA CLIENT
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

server:
  port: 8001
