spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: hruser
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: default
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
