spring:
  application:
    name: hr-user

  spring:
    jpa:
      hibernate:
        ddl-auto: created
  sql:
    init:
      mode: always

  # PROFILE ACTIVE
  profiles:
    active: dev

  # CONFIG SERVER NAME
  config:
    import: optional:configserver:http://localhost:8888/

  h2:
    console:
      enabled: true

# EUREKA CLIENT
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true

server:
  port: ${PORT:0}