spring:
  application:
    name: config-server

  # PROFILE
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/

server:
  port: 8888
